services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:5173"
    volumes:
      - /home/node/app/node_modules
      - .:/home/node/app
  # tests:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.dev
  #   volumes:
  #     - /home/node/app/node_modules
  #     - .:/home/node/app
  #   command: ["npm", "run", "test"]