# Use an official Node.js runtime as a parent image
FROM node:21-alpine

USER node

RUN mkdir -p /home/node/app
# Set the working directory
WORKDIR /home/node/app

# Copy package.json and package-lock.json
COPY --chown=node:node ./package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
# COPY --chown=node:node . .

# Expose the port the app runs on
EXPOSE 5173

# Start the application
CMD ["npm", "run", "dev"]
